services:
  chunk_server_01:
    command: bazel run src/server/chunk_server:run_chunk_server_main -- --config_path=data/config.yml
      --use_docker_dns_server --chunk_server_name=chunk_server_ 01
    container_name: chunk_server_01
    depends_on:
    - master_server_01
    image: gfs-image
    ports:
    - 70001:70001
    restart: unless-stopped
    volumes:
    - ./:/app
    working_dir: /app
  chunk_server_02:
    command: bazel run src/server/chunk_server:run_chunk_server_main -- --config_path=data/config.yml
      --use_docker_dns_server --chunk_server_name=chunk_server_ 02
    container_name: chunk_server_02
    depends_on:
    - master_server_01
    image: gfs-image
    ports:
    - 70002:70002
    restart: unless-stopped
    volumes:
    - ./:/app
    working_dir: /app
  chunk_server_03:
    command: bazel run src/server/chunk_server:run_chunk_server_main -- --config_path=data/config.yml
      --use_docker_dns_server --chunk_server_name=chunk_server_ 03
    container_name: chunk_server_03
    depends_on:
    - master_server_01
    image: gfs-image
    ports:
    - 70003:70003
    restart: unless-stopped
    volumes:
    - ./:/app
    working_dir: /app
  master_server_01:
    build:
      context: .
      dockerfile: Dockerfile
    command: bazel run src/server/master_server:run_master_server_main -- --config_path=data/config.yml
      --use_docker_dns_server --master_name=master_server_01
    container_name: master_server_01
    image: gfs-image
    ports:
    - 60001:60001
    restart: unless-stopped
    volumes:
    - ./:/app
    working_dir: /app
version: '3.7'
